# Generated by Django 3.0.5 on 2020-05-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publish_date',
            new_name='create_at',
        ),
    ]
