# Generated by Django 3.0.5 on 2020-05-30 11:56

from django.db import migrations, models
import django.db.models.deletion
import product.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200530_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.api.models.get_image_filename, verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
