# Generated by Django 3.0.5 on 2020-05-30 12:13

from django.db import migrations, models
import product.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200530_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=product.api.models.get_image_filename),
        ),
    ]
